apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-lambda
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: yace-lambda
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-lambda
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.16.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-lambda-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-lambda-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-lambda-config
          name: yace-lambda-config
        - secret:
            defaultMode: 420
            secretName: yace-lambda-credentials
          name: yace-lambda-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-lambda-config
  namespace: monitoring
data:
  config.yml: |
    discovery:
      jobs:
      - region: us-east-1
        type: lambda
        enableMetricData: true
        metrics:
          - name: Duration
            statistics:
            - Sum
            - Maximum
            - Minimum
            - Average
            period: 600
            length: 300
          - name: Invocations
            statistics:
            - Sum
            period: 600
            length: 300
          - name: Errors
            statistics:
            - Sum
            period: 600
            length: 300
          - name: Throttles
            statistics:
            - Sum
            period: 600
            length: 300
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-lambda-credentials
  namespace: monitoring
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-fargate
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: yace-fargate
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-fargate
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.16.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-fargate-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-fargate-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-fargate-config
          name: yace-fargate-config
        - secret:
            defaultMode: 420
            secretName: yace-fargate-credentials
          name: yace-fargate-credentials

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-fargate-config
  namespace: monitoring
data:
  config.yml: |
    discovery:
      jobs:
      - region: us-east-1
        type: ecs-containerinsights
        enableMetricData: true
        metrics:
          - name: ContainerInstanceCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: ServiceCount
            statistics:
            - Average
            period: 60
            length: 300

      - region: us-east-1
        type: ecs-containerinsights
        enableMetricData: true
        awsDimensions:
          - ServiceName
        metrics:
          - name: CpuReserved
            statistics:
            - Average
            period: 60
            length: 300
          - name: CpuUtilized
            statistics:
            - Average
            period: 60
            length: 300
          - name: MemoryReserved
            statistics:
            - Average
            period: 60
            length: 300
          - name: MemoryUtilized
            statistics:
            - Average
            period: 60
            length: 300
          - name: StorageReadBytes
            statistics:
            - Average
            period: 60
            length: 300
          - name: StorageWriteBytes
            statistics:
            - Average
            period: 60
            length: 300
          - name: NetworkRxBytes
            statistics:
            - Average
            period: 60
            length: 300
          - name: NetworkTxBytes
            statistics:
            - Average
            period: 60
            length: 300
          - name: DesiredTaskCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: TaskCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: PendingTaskCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: RunningTaskCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: DeploymentCount
            statistics:
            - Average
            period: 60
            length: 300
          - name: TaskSetCount
            statistics:
            - Average
            period: 60
            length: 300
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-fargate-credentials
  namespace: monitoring
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yace-elb
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: yace-elb
  replicas: 1
  template:
    metadata:
      labels:
        app: yace-elb
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
      - name: yace
        image: quay.io/invisionag/yet-another-cloudwatch-exporter:v0.16.0-alpha
        ports:
        - containerPort: 5000
        volumeMounts:
          - name: yace-elb-config
            mountPath: /tmp/config.yml
            subPath: config.yml
          - name: yace-elb-credentials
            mountPath: /exporter/.aws/credentials
            subPath: credentials
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      volumes:
        - configMap:
            defaultMode: 420
            name: yace-elb-config
          name: yace-elb-config
        - secret:
            defaultMode: 420
            secretName: yace-elb-credentials
          name: yace-elb-credentials
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yace-elb-config
  namespace: monitoring
data:
  config.yml: |
    discovery:
      jobs:
      - region: us-west-2
        type: elb
        enableMetricData: true
        metrics:
          - name: BackendConnectionErrors
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HealthyHostCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Backend_2XX
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Backend_3XX
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Backend_4XX
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_Backend_5XX
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_4XX
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: HTTPCode_ELB_5XX
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: Latency
            statistics:
            - Average
            - p95
            period: 300
            length: 3600
          - name: RequestCount
            statistics:
            - Sum
            period: 300
            length: 3600
          - name: SpilloverCount
            statistics:
            - Sum
            period: 300
            length: 3600
            nilToZero: true
          - name: SurgeQueueLength
            statistics:
            - Maximum
            period: 300
            length: 3600
            nilToZero: true
          - name: UnHealthyHostCount
            statistics:
            - Minimum
            period: 300
            length: 3600
            nilToZero: true
---
apiVersion: v1
kind: Secret
metadata:
  name: yace-elb-credentials
  namespace: monitoring
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
