{
 "title": "AWS Lambda Golden Signals",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_errors_sum / aws_lambda_invocations_sum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_errors_sum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_throttles_sum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_invocations_sum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Duration total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_sum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Duration (minimum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_minimum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Duration (average)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_average",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  },
  {
   "title": "Duration (maximum)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_lambda_duration_maximum",
     "legendFormat": "Function: {{dimension_FunctionName}}"
    }
   ]
  }
 ]
}