apiVersion: v1
kind: Secret
metadata:
  name: yace-credentials
  namespace: monitoring
data:
  # Add in credentials the result of:
  # cat ~/.aws/credentials | base64
  credentials: |
    XXXXXXXXXXXXXXXXXXXXX